apiVersion: v1
kind: Service
metadata:
  name: pstore-exporter
  labels:
    app.kubernetes.io/name: pstore-exporter
spec:
  selector:
    app.kubernetes.io/name: pstore-exporter
  ports:
    - name: metrics
      port: 9101
      targetPort: metrics
